@startuml
namespace ag_conf基本关系 {
    class Binder << (S,Aquamarine) >> {
        +实现属性绑定
    }
    class Environment << (S,Aquamarine) >> {
        +环境变量及其他配置的统一管理
    }
    class Resolver << (S,Aquamarine) >> {
        +配置获取的具体实现
    }
    class Sources << (S,Aquamarine) >> {
        +配置源的统一管理
    }
    class Source << (S,Aquamarine) >> {
        +配置源的具体实现
    }

    Binder *-- Environment
    Environment *-- Sources
    Environment *-- Resolver
    Resolver *-- Sources
    Sources o-- Source

}